//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLOUSINA
    {
        public int ID { get; set; }
        public int IDTipoCiclo { get; set; }
        public int IDCliente { get; set; }
        public System.DateTime Data { get; set; }
        public int Totalizador { get; set; }
        public int IDReceita { get; set; }
        public int Ciclo { get; set; }
        public int IDTurno { get; set; }
        public System.DateTime DataProducao { get; set; }
        public int IDOperacao { get; set; }
        public int IDCaminhao { get; set; }
        public int Agr1Real { get; set; }
        public int Agr1Prog { get; set; }
        public int Agr2Real { get; set; }
        public int Agr2Prog { get; set; }
        public int Agr3Real { get; set; }
        public int Agr3Prog { get; set; }
        public int Agr4Real { get; set; }
        public int Agr4Prog { get; set; }
        public int Agr5Real { get; set; }
        public int Agr5Prog { get; set; }
        public int Agr6Real { get; set; }
        public int Agr6Prog { get; set; }
        public int UR1 { get; set; }
        public int UR2 { get; set; }
        public int UR3 { get; set; }
        public int UR4 { get; set; }
        public int Cim1Real { get; set; }
        public int Cim1Prog { get; set; }
        public int Cim2Real { get; set; }
        public int Cim2Prog { get; set; }
        public int Cim3Real { get; set; }
        public int Cim3Prog { get; set; }
        public int Cim4Real { get; set; }
        public int Cim4Prog { get; set; }
        public int Agua1Real { get; set; }
        public int Agua1Prog { get; set; }
        public int Adit1Real { get; set; }
        public int Adit1Prog { get; set; }
        public int Adit2Real { get; set; }
        public int Adit2Prog { get; set; }
        public int Adit3Real { get; set; }
        public int Adit3Prog { get; set; }
    
        public virtual RECEITA RECEITA { get; set; }
        public virtual TIPOCICLO TIPOCICLO { get; set; }
        public virtual TURNO TURNO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
