//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESTINO
    {
        public int ID { get; set; }
        public int IDCliente { get; set; }
        public int IDCaminhao { get; set; }
        public int IDPesagem { get; set; }
    
        public virtual FROTA FROTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual PESAGEM PESAGEM { get; set; }
    }
}
