//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTRADA
    {
        public int ID { get; set; }
        public Nullable<int> IDfornecedor { get; set; }
        public Nullable<int> IDInsumo { get; set; }
        public Nullable<System.DateTime> DataEntrada { get; set; }
        public Nullable<double> QtdEntrada { get; set; }
        public Nullable<double> QtdNF { get; set; }
        public string NF { get; set; }
    
        public virtual INSUMO INSUMO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
