//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTOQUE
    {
        public int ID { get; set; }
        public int Agr1Est { get; set; }
        public int Agr2Est { get; set; }
        public int Agr3Est { get; set; }
        public int Agr4Est { get; set; }
        public int Agr5Est { get; set; }
        public int Agr6Est { get; set; }
        public int UR1Est { get; set; }
        public int UR2Est { get; set; }
        public int UR3Est { get; set; }
        public int UR4Est { get; set; }
        public int Cim1Est { get; set; }
        public int Cim2Est { get; set; }
        public int Cim3Est { get; set; }
        public int Cim4Est { get; set; }
        public int AguaEst { get; set; }
        public int Adit1Est { get; set; }
        public int Adit2Est { get; set; }
        public int Adit3Est { get; set; }
    }
}
