//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class FROTA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FROTA()
        {
            this.DESTINO = new HashSet<DESTINO>();
            this.PESAGEM = new HashSet<PESAGEM>();
        }
    
        public int ID { get; set; }
        public string Placa { get; set; }
        public string Marca { get; set; }
        public double Tara { get; set; }
        public double PesoBruto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DESTINO> DESTINO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PESAGEM> PESAGEM { get; set; }
    }
}
