//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INSUMO()
        {
            this.ENTRADA = new HashSet<ENTRADA>();
        }
    
        public int ID { get; set; }
        public int IDTipoInsumo { get; set; }
        public double QtdEstoque { get; set; }
        public double QtdMinima { get; set; }
        public int IDSilo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ENTRADA> ENTRADA { get; set; }
        public virtual SILO SILO { get; set; }
        public virtual TIPOINSUMO TIPOINSUMO { get; set; }
    }
}
