//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UsinaEntities : DbContext
    {
        public UsinaEntities()
            : base("name=UsinaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CICLOUSINA> CICLOUSINA { get; set; }
        public virtual DbSet<DESTINO> DESTINO { get; set; }
        public virtual DbSet<ENTRADA> ENTRADA { get; set; }
        public virtual DbSet<ESTOQUE> ESTOQUE { get; set; }
        public virtual DbSet<FROTA> FROTA { get; set; }
        public virtual DbSet<FUNCAO> FUNCAO { get; set; }
        public virtual DbSet<INSUMO> INSUMO { get; set; }
        public virtual DbSet<PESAGEM> PESAGEM { get; set; }
        public virtual DbSet<RECEITA> RECEITA { get; set; }
        public virtual DbSet<SILO> SILO { get; set; }
        public virtual DbSet<TIPOCICLO> TIPOCICLO { get; set; }
        public virtual DbSet<TIPOINSUMO> TIPOINSUMO { get; set; }
        public virtual DbSet<TURNO> TURNO { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
