//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supervisorio.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEITA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEITA()
        {
            this.CICLOUSINA = new HashSet<CICLOUSINA>();
        }
    
        public int ID { get; set; }
        public int IDCliente { get; set; }
        public string Nome { get; set; }
        public int IDOperacao { get; set; }
        public int Agr1Prog { get; set; }
        public int Agr2Prog { get; set; }
        public int Agr3Prog { get; set; }
        public int Agr4Prog { get; set; }
        public int Agr5Prog { get; set; }
        public int Agr6Prog { get; set; }
        public int Cim1Prog { get; set; }
        public int Cim2Prog { get; set; }
        public int Cim3Prog { get; set; }
        public int Agua1Prog { get; set; }
        public int Adit1Prog { get; set; }
        public int Adit2Prog { get; set; }
        public int Adit3Prog { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CICLOUSINA> CICLOUSINA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
